In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2, 3],
                [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[8, 7],
       [9, 9],
       [1, 9],
       [1, 5],
       [8, 7],
       [6, 6],
       [0, 4]])

In [11]:
np.random.random((3, 5))

array([[0.75480126, 0.63027896, 0.00432216, 0.82660043, 0.76376716],
       [0.85392685, 0.22136242, 0.51595776, 0.57397845, 0.87653345],
       [0.21496518, 0.99913323, 0.29537964, 0.31380183, 0.59812565]])

In [12]:
np.random.seed(42)

np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
array = np.random.randint(1, 10, size=(3, 7))

np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
array[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
a4 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [18]:
a4 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
ones = np.ones((5, 3))

In [20]:
a4 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
ones = np.ones((3, 5))

In [22]:
a4 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [23]:
a4 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
a4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [25]:
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [26]:
np.mean(a4)

3.8666666666666667

In [27]:
np.max(a4)

9

In [28]:
np.min(a4)

0

In [29]:
np.std(a4)

2.578543947441829

In [30]:
np.var(a4)

6.648888888888889

In [31]:
a4.reshape(3, 5, 1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
a4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [33]:
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

In [34]:
np.dot(mat1, mat2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [35]:
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [37]:
np.dot(mat3.T, mat4)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

In [38]:
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))

In [39]:
mat5 > mat6

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

What happens when you compare the arrays with `>`?

In [40]:
mat5 >= mat6

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [41]:
mat5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [42]:
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [43]:
np.sort(mat5)

array([[6, 6],
       [4, 7],
       [2, 7],
       [2, 5]])

In [44]:
np.argsort(mat6)

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0]])

In [45]:
np.argmax(mat5)

2

In [46]:
np.argmin(mat6)

0

In [47]:
np.argmax(mat5, axis=1)

array([0, 0, 1, 0])

In [48]:
np.argmin(mat6, axis=0)

array([0, 0])

In [49]:
np.random.randn(3, 5)

array([[-0.03582604,  1.56464366, -2.6197451 ,  0.8219025 ,  0.08704707],
       [-0.29900735,  0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704,  0.91540212]])

In [50]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])